name: test-and-deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
      - run: npm test
  deploy:
    runs-on: ubuntu-latest
    env:
      JWT_ACCESS_SECRET: access
      JWT_REFRESH_SECRET: refresh
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd projects/learning-base
            git clone git@github.com:AlexanderKulia/learning-base-backend.git
            echo 'Deployed successfully'
